FROM registry.redhat.io/ubi8/ubi-minimal:latest
WORKDIR /usr/src/app
ARG SERVICE_HOST
ENV API_HOST=${SERVICE_HOST:+$SERVICE_HOST}
ENV API_HOST=${SERVICE_HOST:-localhost}

USER 0

RUN microdnf install nginx

ADD dist ./dist
RUN ["rm", "-rfv", "/usr/share/nginx/html"]
RUN ["cp", "-rfv", "/usr/src/app/dist", "/usr/share/nginx/html"]
COPY nginx.conf /etc/nginx/nginx.conf
RUN sed -i s/API_HOST/$API_HOST/g /etc/nginx/nginx.conf

USER 100
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
