FROM registry.redhat.io/ubi8/ubi-minimal:latest

WORKDIR /usr/src/app

USER 0

RUN microdnf module disable nodejs && \
    microdnf module enable nodejs:16
RUN microdnf install nodejs nginx

COPY package.json package-lock.json ./
RUN npm install

COPY src ./src
COPY .eslintrc.yml .
