apiVersion: v1
kind: Template
metadata:
  name: payload-tracker-frontend
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: payload-tracker-frontend
    name: payload-tracker-frontend
  minReplicas: ${{MIN_REPLICAS}}
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 9
    selector:
      matchLabels:
        app: payload-tracker-frontend
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: payload-tracker-frontend
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - payload-tracker-frontend
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - payload-tracker-frontend
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - image: quay.io/cloudservices/payload-tracker-frontend:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          name: payload-tracker-frontend
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUESTS}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/nginx/nginx.conf
            name: payload-tracker-nginx-conf
            subPath: nginx.conf
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: payload-tracker-nginx-conf
          name: payload-tracker-nginx-conf
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: payload-tracker-frontend
    name: payload-tracker-frontend
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: payload-tracker-frontend
    sessionAffinity: None
    type: ClusterIP
parameters:
- description: Name of the Payload Tracker URL for the API
  name: PAYLOAD_TRACKER_URL
  value: http://payload-tracker-api:8000
- description: Cpu limit of service
  name: CPU_LIMIT
  value: 500m
- description: memory limit of service
  name: MEMORY_LIMIT
  value: 512Mi
- description: cpu requests of service
  name: CPU_REQUEST
  value: 200m
- description: memory requests of service
  name: MEMORY_REQUESTS
  value: 256Mi
- description: The number of replicas to use for the prometheus deployment
  name: REPLICAS
  value: '3'
- description: The minimum number of replicas to use for the payload-tracker-frontend
  name: MIN_REPLICAS
  value: '3'
- description: Image tag
  name: IMAGE_TAG
  required: true
